import * as THREE from 'three';

export interface GeometryWithOffset {
  geom: THREE.BufferGeometry;
  zOffset?: number;
}

/**
 * Converte um ou mais BufferGeometries em um ArrayBuffer binário STL padrão de alta performance
 */
export function exportToBinarySTL(
  items: (THREE.BufferGeometry | GeometryWithOffset)[]
): ArrayBuffer {
  // Normaliza entradas
  const normalizedItems: GeometryWithOffset[] = items.map((item) => {
    if ('geom' in item) {
      return item;
    }
    return { geom: item, zOffset: 0 };
  });

  // 1. Coleta todas as faces e vértices
  let totalTriangles = 0;

  const preparedGeoms = normalizedItems.map(({ geom, zOffset = 0 }) => {
    let nonIndexedGeom = geom;
    if (geom.index) {
      nonIndexedGeom = geom.toNonIndexed();
    }
    const pos = nonIndexedGeom.attributes.position;
    const triangles = pos ? pos.count / 3 : 0;
    totalTriangles += triangles;
    return { geom: nonIndexedGeom, triangles, zOffset };
  });

  // Tamanho do arquivo STL: 80 bytes cabeçalho + 4 bytes contagem de triângulos + 50 bytes por triângulo
  const bufferLength = 80 + 4 + totalTriangles * 50;
  const arrayBuffer = new ArrayBuffer(bufferLength);
  const dataView = new DataView(arrayBuffer);

  // Cabeçalho STL de 80 bytes (ASCII)
  const header = 'Binary STL generated by Letra Caixa 3D MakerWorld Generator';
  for (let i = 0; i < 80; i++) {
    dataView.setUint8(i, i < header.length ? header.charCodeAt(i) : 0x20);
  }

  // Contagem de triângulos (uint32 Little Endian)
  dataView.setUint32(80, totalTriangles, true);

  let offset = 84;
  const pA = new THREE.Vector3();
  const pB = new THREE.Vector3();
  const pC = new THREE.Vector3();
  const cb = new THREE.Vector3();
  const ab = new THREE.Vector3();
  const normal = new THREE.Vector3();

  preparedGeoms.forEach(({ geom, triangles, zOffset }) => {
    const pos = geom.attributes.position;
    if (!pos) return;

    for (let i = 0; i < triangles; i++) {
      const idx = i * 3;

      pA.fromBufferAttribute(pos, idx);
      pB.fromBufferAttribute(pos, idx + 1);
      pC.fromBufferAttribute(pos, idx + 2);

      pA.z += zOffset;
      pB.z += zOffset;
      pC.z += zOffset;

      // Calcula o vetor normal da face
      cb.subVectors(pC, pB);
      ab.subVectors(pA, pB);
      cb.cross(ab);
      cb.normalize();
      normal.copy(cb);

      // Normal (nx, ny, nz)
      dataView.setFloat32(offset, normal.x, true);
      dataView.setFloat32(offset + 4, normal.y, true);
      dataView.setFloat32(offset + 8, normal.z, true);

      // Vértice 1 (x, y, z)
      dataView.setFloat32(offset + 12, pA.x, true);
      dataView.setFloat32(offset + 16, pA.y, true);
      dataView.setFloat32(offset + 20, pA.z, true);

      // Vértice 2 (x, y, z)
      dataView.setFloat32(offset + 24, pB.x, true);
      dataView.setFloat32(offset + 28, pB.y, true);
      dataView.setFloat32(offset + 32, pB.z, true);

      // Vértice 3 (x, y, z)
      dataView.setFloat32(offset + 36, pC.x, true);
      dataView.setFloat32(offset + 40, pC.y, true);
      dataView.setFloat32(offset + 44, pC.z, true);

      // Attribute byte count (0)
      dataView.setUint16(offset + 48, 0, true);

      offset += 50;
    }
  });

  return arrayBuffer;
}

/**
 * Dispara o download de um Blob no navegador com nome amigável
 */
export function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 1500);
}
